apiVersion: application.sample.ibm.com/v1beta1
kind: Application
metadata:
  name: application2
spec:
  version: "1.0.0"
  amountPods: 2
  databaseName: database
  databaseNamespace: database
  title: Movies